# Find the Dockerfile for mcr.microsoft.com/azure-functions/powershell:4-powershell7.2 at this URL
# https://github.com/Azure/azure-functions-docker/blob/dev/host/4/bullseye/amd64/powershell/powershell72

FROM mcr.microsoft.com/azure-functions/powershell:4-powershell7.2
